modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://github.com/devsavage/savagecore/issues"
license="MIT"

[[mods]]
    modId="savagecore"
    version="${file.jarVersion}"
    displayName="SavageCore"
    updateJSONURL="https://api.savagedev.io/mc-mods/savagecore/versions?forge=true&version=1.17.1"
    displayURL="https://nlcc.savagedev.io/minecraft-mods/savagecore"
    authors="savagedev"
    description='''
    Shared library mod required by (most) mods from savagedev
    '''

[[dependencies.savagecore]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.savagecore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18]"
    ordering="NONE"
    side="BOTH"
